### ISSUE TITLE
Code 101 error

### ISSUE THREAD

**Issue by TomRaikes** [atesh/XKit#212]
I keep getting this, saying Can't reach Xkit Servers. I have reinstalled Xkit several times with no luck :(

**Comment by thejamespower** [comment]
Same here, Chrome on Mac OS X. Reset Xkit at modal prompt, now cannot access any of the extension functionality at all...

**Comment by TomRaikes** [comment]
Chrome plus Mac OS X also if that helps!

**Comment by Wolvan** [comment]
Old XKit's Server are not functional anymore, you can use New XKit instead

**Comment by TomRaikes** [comment]
Wolvan, I have the latest version of XKit installed and it gives the same error

**Comment by Wolvan** [comment]
Do you still have old xkit installed with new xkit?

**Comment by TomRaikes** [comment]
No, I removed it from Chrome and reinstalled it

**Comment by Wolvan** [comment]
This is a issue on old XKit though, so not really in our control

**Comment by TomRaikes** [comment]
So what can I do to fix it?

**Comment by Wolvan** [comment]
Check again the version of XKit you have installed. 7.5.1 is old XKit, 7.7.1 is New XKit

**Comment by TomRaikes** [comment]
I have 7.7.1

**Comment by bregger** [comment]
The SSL certificate for https://www.xkitcs.com has expired.

**Comment by makmanalp** [comment]
Same here on 7.5.1, looks like!

**Comment by maik-kulbe** [comment]
I don't wanna be the bad guy here, but the dev should either update that frickin cert(goddamn, it's 4 or 5 clicks and absolutely no cost on startssl or let's encrypt) or at least let someone else run the servers for the extension.

As someone who runs an extension that is used by half a million people, the dev has a certain responsibility and can't just quit. I've seen this often enough and on a human level it's just not okay to do that.

**Comment by Wolvan** [comment]
I agree with you, @maik-kulbe. Or he should at least make an updating to `xkit_preferences` or something telling the people the extension is dead

**Comment by mkzero** [comment]
I don't wanna be the bad guy here, but the dev should either update that frickin cert(goddamn, it's 4 or 5 clicks and absolutely no cost on startssl or let's encrypt) or at least let someone else run the servers for the extension.

As someone who runs an extension that is used by half a million people, the dev has a certain responsibility and can't just quit. I've seen this often enough and on a human level it's just not okay to do that.

**Comment by mrjnumber1** [comment]
he quit development on this project because he got harassed by users with death threats. someone claimed to be molested with no proof. it's the tumblr community, after all.

**Comment by mkzero** [comment]
@mrjnumber1 I don't care what the devs personal problems with the community where - if you want to quit because of such things you at least hand the project over to someone else.

**Comment by Wolvan** [comment]
@mkzero he kind of did. The project was open source so anyone could just take it over, like new-xkit/XKit did

**Comment by mkzero** [comment]
@Wolvan so what's with the code he did not release? That's - under the license code, breach of the license. And what about the servers that broke the extension with their outdated SSL certs? Sorry, but just throwing some code at the public is not handing over the project.

**Comment by Wolvan** [comment]
What do you mean, "Code he did not release"? There isn't anything he did not release afaik.

**Comment by mkzero** [comment]
@Wolvan from my research there's some plugin code missing. Sure, you could pull it into the browser, but then the git history is missing - which is more than important in any project. Also, could you setup an update server? Haven't seen anything for that...

**Comment by Wolvan** [comment]
Update server? As in Auto-updating the Plugins for Chrome and Firefox? there's New XKit with working servers.
I still honestly don't know what plugin code is supposed to be missing. We had everything in our fork afaik

**Comment by mkzero** [comment]
@Wolvan okay, let's be totally clear here: You don't seem to get the general problem. You don't have any way to notice users and the old extension and domain gets more useless over time without anyone having access. If you worked in IT(not just as a stackoverflow-copy-paste-devop but as someone who has to care for users and co-workers) you'd know that this is totally unaccepteable. This is the same bs ideology like many other projects have - noone to care for in case of a sudden disappearance of the main dev. Rule no. 1 as admin: Always document and share like you expect to get hit by a bus at any given moment.

**Comment by Wolvan** [comment]
That might be for a commercial project, yes. But keep in mind, atesh has not been payed for this. In fact, he did this as a hobby and is did absolutely not owe anybody continuing to work on this extension

**Comment by SpeedyD** [comment]
How about this bickering just finally ends already. So there's things
missing- the New xKit group is doing fine without it all.

There's one thing you seem to forget; Atesh was doing it for free. Even the
paid mobile version had every last cent going into the actual development,
instead of himself.

He was bullied merciless for a crime he didn't commit and here you're
basically trampling on him while he's already down and out- if you know
everything so well, why don't you start your own project for absolutely
nothing in return and we'll see how things go then.

Just.. quit this nonsense. It's useless, futile and frankly you're just a
dick, mkzero.



2015-12-28 0:09 GMT+01:00 mkzero <notifications@github.com>:

**Comment by Wolvan** [comment]
My apologies, @SpeedyD and @mkzero

**Comment by mkzero** [comment]
Goddammit, how about you all get your shit together and understand that personal problems are personal problems and coding for millions of people - even when done as a hobby - brings a certain responsibility with it.. And it's just not okay to throw in the personal bs he had to go through. Bailing out because ppl harassed him is just as well a dick move as the ppl harassing him. Sustainable code, docs and servers are vital to *every* project. Imagine the mozilla or apache projects having just one main maintainer that quits like him. Would it be okay to tell millions firefox won't get updates because people harassed someone so they have to install some other (forked) software? No. It wouldn't. Atesh was a SPOF and with that he earned his part of tech-rage, like any other skript kiddy who thinks they can be some hero on their own.

**Comment by SpeedyD** [comment]
@Wolvan- complaint wasn't aimed at you.

@mkzero is just being loud and obnoxious, basically serving only as an
awkward distraction. In all honesty, even if they had a good point, it was
lost likely at the same time when they lost their compassion for their
fellow man. At this point, I'm quite unsure whether they were trying to
raise an actual point or if they're just trying to be very elaborate with
their trolling, Wolvan.

2015-12-28 0:23 GMT+01:00 mkzero <notifications@github.com>:

**Comment by Wolvan** [comment]
So I ain't the only one that feels like this is a massive troll? I really hoped it's just some uneducated fool that has no idea how the world works

**Comment by SpeedyD** [comment]
Frankly, I've felt like the guy was a troll ever since their first message
was copying the complaint another person had already made. There seems to
be a complete and utter lack of compassion in their replies and that's
usually a good indicator.

2015-12-28 0:41 GMT+01:00 Wolvan <notifications@github.com>:

**Comment by Wolvan** [comment]
Eh, doesn't hurt to try and educate people

**Comment by SpeedyD** [comment]
True, but looking at the amount of messages, I feel strongly that you've
wasted your time, and that's something I find quite saddening.

Anyway, I'll leave you be for now, Wolvan. You have a nice day.. and
seriously.. just.. ignore him. It's not worth it.

2015-12-28 0:44 GMT+01:00 Wolvan <notifications@github.com>:

**Comment by mkzero** [comment]
Wow. Kids who think they know how the world works and stamp me as a troll. slow-clap.gif

You apparently haven't worked in pro IT and both of you don't know what problems arise with your carelessness. So please step back a few steps until you learned some basic skills for sustainable software. Just a little example for your "arguments" that he did this in his free time: Our local Freifunk community got 100-200 users and everyone and everything is replaceable and redundant. And this is all voluntary work for the community in our free time. So please, don't think you know how IT and free software works just because you copy-pasted some code from Stackoverflow.

**Comment by TomRaikes** [comment]
Oh my god. Oh my good god. @mkzero just stop before you sound like even more of a petulant child than you have already. Nobody cares if you have knowledge of commercial or community IT projects. In case you didn't know github issues is not the place to discuss how projects should be managed or how you would do it differently, it's for reporting issues I'm the hope that others may be able to help. I should have closed this issue a long time ago before this sort of thing came up.
